repos:
  - repo: local
    hooks:
      - id: update-requirements
        name: update-requirements
        entry: ./scripts/update_requirements.sh
        language: script
  - repo: local
    hooks:
      - id: run-test
        name: run-test
        entry: ./scripts/run_tests.sh
        language: script